-- ============================================================================
-- Phase 11 — application users (authentication & authorization).
--
-- Stores ONLY the identity record needed for authentication:
--
--     id            UUID primary key (generated by the application)
--     username      TEXT, UNIQUE NOT NULL  -- login handle
--     password_hash TEXT NOT NULL          -- Argon2id hash, never plaintext
--     created_at    TIMESTAMPTZ NOT NULL   -- registration time
--     updated_at    TIMESTAMPTZ NOT NULL   -- metadata only
--
-- Security model
-- --------------
-- * Passwords are NEVER stored in plaintext; only the Argon2id hash lives
--   here. The hash is treated as a secret too: it is never returned by the
--   API and never logged.
-- * The UNIQUE constraint on username IS the race-safe duplicate guard. A
--   concurrent second INSERT for the same username raises a unique-violation,
--   which the user repository translates into the structured 409
--   ``username_exists`` error. Callers must NOT rely on a pre-check.
-- * Raw keyboard/mouse events, behavioural embeddings, JWT secrets and any
--   other data never belong in this table.
--
-- The migration is idempotent (CREATE TABLE IF NOT EXISTS) and leaves the
-- Phase 10 behavioral_profiles table untouched.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id            UUID        PRIMARY KEY,
    username      TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT users_username_non_blank CHECK (length(btrim(username)) > 0)
);

COMMIT;